Repository Waste-Not-Want-Not/waste-not, pull requests merged in 2022-08, with the labels that each got.

#4 Create pull_request_template.md
  docs/pull_request_template.md
Labels: documentation

#19 FE | Update PR Template
  docs/pull_request_template.md
Labels: documentation, FE

#20 FE | Initial GraphQL Query
  package-lock.json
  package.json
  src/components/Kitchen/Kitchen.css
  src/components/Kitchen/Kitchen.js
  src/components/Preview/Preview.css
  src/components/Preview/Preview.js
  src/graphql/queries.js
  src/index.js
Labels: enhancement, FE

#21 FE | Feat/build location component
  package-lock.json
  src/components/App/App.js
  src/components/Kitchen/Kitchen.js
  src/components/Location/Location.css
  src/components/Location/Location.js
Labels: FE
