Repository Waste-Not-Want-Not/waste-not, pull requests merged in 2022-09, with the labels that each got.

#28 FE | Feat/possible donation page
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/ItemCard/ItemCard.js
  src/components/Kitchen/Kitchen.js
  src/components/Location/Location.js
  src/components/PossibleDonations/PossibleDonations.css
  src/components/PossibleDonations/PossibleDonations.js
Labels: enhancement, FE

#30 FE | Styling/page layouts
  src/components/Donation/Donation.css
  src/components/Donation/Donation.js
  src/components/Donations/Donations.css
  src/components/Donations/Donations.js
  src/components/DonationsPage/DonationsPage.css
  src/components/FoodBankForm/FoodBankForm.css
  src/components/FoodBankForm/FoodBankForm.js
  src/components/ItemCard/ItemCard.css
  src/components/ItemCard/ItemCard.js
  src/components/Kitchen/Kitchen.css
  src/components/Kitchen/Kitchen.js
  src/components/Location/Location.css
  src/components/Location/Location.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/PossibleDonations/PossibleDonations.css
  src/components/PossibleDonations/PossibleDonations.js
  src/components/Preview/Preview.css
  src/index.css
Labels: enhancement, FE

#31 FE | Feat/intro page
  package-lock.json
  src/components/App/App.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Overview/Overview.css
  src/components/Overview/Overview.js
Labels: FE

#32 FE | Feat/create item page
  src/components/App/App.js
  src/components/ItemCard/ItemCard.js
  src/components/ItemForm/ItemForm.js
  src/components/Kitchen/Kitchen.js
  src/graphql/mutations.js
Labels: FE

#40 Testing/build initial tests
  cypress/e2e/kitchen.cy.js
  cypress/e2e/overview.cy.js
  cypress/e2e/spec.cy.js
Labels: FE

#43 Feat/delete donation items
  src/components/Donations/Donations.js
  src/components/ItemCard/ItemCard.css
  src/components/ItemCard/ItemCard.js
  src/components/Location/Location.js
  src/graphql/mutations.js
  src/graphql/queries.js
Labels: FE

#45 Testing/possible donations and donations page
  cypress/e2e/donation-page.cy.js
  cypress/e2e/possible-donations.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/possible-donations-fixture.json
  package-lock.json
  package.json
  src/components/Donations/Donations.js
  src/components/FoodBankForm/FoodBankForm.js
  src/components/Navbar/Navbar.js
  src/components/PossibleDonations/PossibleDonations.js
Labels: testing

#49 Testing/update tests for ci
  cypress/e2e/freezer.cy.js
  cypress/e2e/fridge.cy.js
  cypress/e2e/kitchen.cy.js
  cypress/e2e/pantry.cy.js
  cypress/e2e/possible-donations.cy.js
Labels: FE

#50 Refactor/codebase and styling
  cypress/downloads/downloads.html
  cypress/e2e/donation-page.cy.js
  cypress/e2e/freezer.cy.js
  cypress/e2e/fridge.cy.js
  cypress/e2e/kitchen.cy.js
  cypress/e2e/overview.cy.js
  cypress/e2e/pantry.cy.js
  cypress/e2e/possible-donations.cy.js
  public/app-logo.png
  src/assets/app-logo.png
  src/assets/donation.png
  src/assets/kitchen-icon.png
  src/assets/overview.png
  src/components/Donation/Donation.css
  src/components/Donation/Donation.js
  src/components/Donations/Donations.js
  src/components/FoodBankForm/FoodBankForm.css
  src/components/ItemCard/ItemCard.css
  src/components/ItemCard/ItemCard.js
  src/components/ItemForm/ItemForm.css
  src/components/Kitchen/Kitchen.css
  src/components/Location/Location.css
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Overview/Overview.css
  src/components/Overview/Overview.js
  src/components/PossibleDonations/PossibleDonations.css
  src/components/PossibleDonations/PossibleDonations.js
  src/components/Preview/Preview.css
  src/components/Preview/Preview.js
  src/index.css
  src/index.js
Labels: FE, testing, styling

#51 Add README.md
  README.md
Labels: documentation
